import { closeSync, existsSync, fsyncSync, mkdirSync, mkdtempSync, openSync, readdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import nodePath from "node:path";
import nodeProcess from "node:process";
import puppeteer, { type Page } from "puppeteer-core";
import { SITE_BROWSER_CHECK_IDS } from "./site-browser-check-ids.ts";

const DOCS = ["combat-mathematics", "ability-calculations", "skills-and-crafting", "equipment-and-value", "endgame-systems"] as const;
const TABLES = ["classes", "enemies", "abilities", "recipes", "gathering-nodes", "items", "gems", "affixes", "shops"] as const;
const SEARCHES = ["defense", "ability", "craft", "tower"] as const;
const VIEWPORTS = [{ id: "1440x900", width: 1440, height: 900 }, { id: "390x844", width: 390, height: 844 }, { id: "320x700", width: 320, height: 700 }] as const;
const ROUTES = ["/", "/mechanics/", "/mechanics/combat-mathematics/", "/mechanics/ability-calculations/", "/mechanics/skills-and-crafting/", "/mechanics/equipment-and-value/", "/mechanics/endgame-systems/", "/items/", "/items/eclipse_gem_ruby/", "/abilities/", "/classes/", "/progression/", "/query/", "/sheets/"] as const;
const GUIDE_ROUTES: Record<string, string> = Object.fromEntries(DOCS.map((id) => [id, `/mechanics/${id}/`]));
const GUIDE_FOR_TABLE: Record<string, string> = { classes: "combat-mathematics", enemies: "combat-mathematics", abilities: "ability-calculations", recipes: "skills-and-crafting", "gathering-nodes": "skills-and-crafting", items: "equipment-and-value", gems: "equipment-and-value", affixes: "equipment-and-value", shops: "equipment-and-value" };
const DATA_TABLE_FOR_CHECK: Record<string, string> = { "gathering-nodes": "gathering_nodes", shops: "shop_listings" };
const DATA_SLUG_FOR_CHECK: Record<string, string> = { shops: "shop-listings" };
const FORBIDDEN = [/\b[0-9a-f]{64}\b/i, /(?:index|gameview|chunk|assets)[-_][A-Za-z0-9]{6,}\.(?:js|html)/i, /\b(?:GameView|getIncomingDefenseMitigation|getCritOverflowDamageBonus|evalComposition|sourceTarget|contractSha256|probeRuntimeSha256)\b/];

type Rec = Record<string, unknown>;
type Result = { id: string; status: "PASS" | "FAIL" | "SKIPPED"; detail: string };
type Text = { id: string; text: string; evidence: { kind: string; requiredProbes: Probe[] } };
type Probe = { suite: string; id: string; category: string | null; contractSha256: string; promotionEligible: boolean };
function rec(value: unknown): Rec { if (typeof value !== "object" || value === null || Array.isArray(value)) throw new Error("expected object"); return value; }
function str(value: unknown, name: string): string { const object = rec(value); if (typeof object[name] !== "string") throw new Error(`missing ${name}`); return object[name]; }
function arr(value: unknown, name: string): unknown[] { const object = rec(value); if (!Array.isArray(object[name])) throw new Error(`missing ${name}`); return object[name]; }
function probe(value: unknown): Probe { const object = rec(value); if (typeof object.suite !== "string" || typeof object.id !== "string" || (typeof object.category !== "string" && object.category !== null) || typeof object.contractSha256 !== "string" || typeof object.promotionEligible !== "boolean") throw new Error("invalid probe"); return { suite: object.suite, id: object.id, category: object.category, contractSha256: object.contractSha256, promotionEligible: object.promotionEligible }; }
function text(value: unknown): Text { const object = rec(value); const evidence = rec(object.evidence); if (typeof object.id !== "string" || typeof object.text !== "string" || typeof evidence.kind !== "string" || !Array.isArray(evidence.requiredProbes)) throw new Error("invalid mechanic text"); return { id: object.id, text: object.text, evidence: { kind: evidence.kind, requiredProbes: evidence.requiredProbes.map(probe) } }; }
function doc(value: unknown): Rec { const object = rec(value); if (typeof object.id !== "string") throw new Error("invalid mechanic document"); return object; }
function docs(value: unknown): Rec[] { const object = rec(value); if (!Array.isArray(object.documents)) throw new Error("mechanics documents missing"); return object.documents.map(doc); }
function textList(document: Rec): Text[] { const output: Text[] = [text(document.title), text(document.summary)]; for (const sectionValue of arr(document, "sections")) { const section = rec(sectionValue); output.push(text(section.title), ...arr(section, "paragraphs").map(text), ...arr(section, "bullets").map(text)); for (const formulaValue of arr(section, "formulas")) { const formula = rec(formulaValue); output.push(text(formula.label), text(formula.expression)); if (formula.note !== null) output.push(text(formula.note)); } for (const factValue of arr(section, "facts")) { const fact = rec(factValue); output.push(text(fact.label), text(fact.value)); } } for (const linkValue of arr(document, "related")) output.push(text(rec(linkValue).label)); return output; }
function formulaAndFactTexts(document: Rec): Text[] { const output: Text[] = []; for (const sectionValue of arr(document, "sections")) { const section = rec(sectionValue); for (const formulaValue of arr(section, "formulas")) { const formula = rec(formulaValue); output.push(text(formula.label), text(formula.expression)); if (formula.note !== null) output.push(text(formula.note)); } for (const factValue of arr(section, "facts")) { const fact = rec(factValue); output.push(text(fact.label), text(fact.value)); } } return output; }
function gameFormulaText(mechanics: Rec): string { for (const document of docs(mechanics)) { const formula = formulaAndFactTexts(document).find((item) => item.evidence.kind === "game-authored" && item.text.startsWith("M = D /")); if (formula !== undefined) return formula.text; } throw new Error("game-authored mitigation formula missing"); }
function detailId(value: Rec): string | null { if (typeof value.id === "string") return value.id; if (typeof value.item_id === "string") return value.item_id; if (typeof value.key === "string") return value.key; return null; }
function canonical(value: unknown): string { if (value === null || typeof value !== "object") return JSON.stringify(value); if (Array.isArray(value)) return `[${value.map(canonical).join(",")}]`; const object = value as Rec; return `{${Object.keys(object).sort().map((key) => `${JSON.stringify(key)}:${canonical(object[key])}`).join(",")}}`; }
function expectedStatus(item: Text, mechanics: Rec, runtime: Rec): string { if (item.evidence.kind === "editorial") return "editorial"; const requirements = item.evidence.requiredProbes; if (!requirements.some((entry) => entry.promotionEligible)) return "source-verified"; const contracts = arr(mechanics, "probeContracts"); const results = arr(runtime, "results"); for (const requirement of requirements) { const contract = contracts.find((value) => { const object = rec(value); return object.suite === requirement.suite && object.id === requirement.id && (object.category ?? null) === requirement.category && object.contractSha256 === requirement.contractSha256; }); const result = results.find((value) => { const object = rec(value); return object.suite === requirement.suite && object.id === requirement.id && (object.category ?? null) === requirement.category && object.contractSha256 === requirement.contractSha256; }); if (contract === undefined || result === undefined) return "source-verified"; const contractObject = rec(contract); const resultObject = rec(result); if (resultObject.status !== "PASS" || !Array.isArray(contractObject.cases) || !Array.isArray(resultObject.cases) || contractObject.cases.length !== resultObject.cases.length) return "source-verified"; for (let index = 0; index < contractObject.cases.length; index += 1) { const expected = rec(contractObject.cases[index]); const observed = rec(resultObject.cases[index]); if (expected.id !== observed.id || canonical(expected.input) !== canonical(observed.input) || canonical(expected.expected) !== canonical(observed.expected) || canonical(observed.firstObserved) !== canonical(expected.expected) || canonical(observed.secondObserved) !== canonical(expected.expected)) return "source-verified"; } } return "live-verified"; }
async function getJson(page: Page, path: string): Promise<unknown> { return page.evaluate(async (url) => { const response = await fetch(url); if (!response.ok) throw new Error(`${url} ${response.status}`); return response.json(); }, path); }
async function go(page: Page, base: string, route: string): Promise<void> { const response = await page.goto(new URL(route, base).href, { waitUntil: "domcontentloaded" }); if (response === null || !response.ok()) throw new Error(`failed to load ${route}`); }
async function visibleText(page: Page): Promise<string> { return page.evaluate(() => `${document.body.innerText}\n${Array.from(document.querySelectorAll("[aria-label],[title]"), (node) => `${node.getAttribute("aria-label") ?? ""} ${node.getAttribute("title") ?? ""}`).join("\n")}`); }
function htmlFiles(root: string): string[] { if (!existsSync(root)) throw new Error(`missing build ${root}`); const files: string[] = []; for (const entry of readdirSync(root, { withFileTypes: true })) { const file = nodePath.join(root, entry.name); if (entry.isDirectory()) files.push(...htmlFiles(file)); else if (entry.name.endsWith(".html")) files.push(file); } return files; }
function localIds(): string[] { const prefix = (name: string, values: readonly string[]) => values.map((value) => `${name}.${value}`); return [...prefix("guide-contract", DOCS), ...prefix("guide-text", DOCS), ...prefix("guide-hrefs", DOCS), ...prefix("guide-provenance", DOCS), ...prefix("index-card", DOCS), ...prefix("mapped-link", TABLES), ...prefix("search", SEARCHES), ...prefix("responsive", VIEWPORTS.map((entry) => entry.id)), ...prefix("no-internals", ROUTES), ...prefix("smoke", ROUTES), "endgame-copy", "endgame-counts", "progression-links", "combobox-ids", "lazy-search-transfer", "search-keyboard", "desktop-fold", "eager-image", "art-variants", "transfer-budget", "prerender-content"]; }
function atomicWrite(file: string, value: unknown): void { const directory = nodePath.dirname(file); mkdirSync(directory, { recursive: true }); const tempDirectory = mkdtempSync(nodePath.join(directory, ".site-browser-")); const temp = nodePath.join(tempDirectory, "checks.json"); const descriptor = openSync(temp, "w"); try { writeFileSync(descriptor, `${canonical(value)}\n`); fsyncSync(descriptor); } finally { closeSync(descriptor); } renameSync(temp, file); }

export type VerifySiteBrowserOptions = { url: string; executablePath?: string; resultPath?: string };
export async function verifySiteBrowser(options: VerifySiteBrowserOptions): Promise<Result[]> {
  const checks: Result[] = []; const seen = new Set<string>();
  const emit = async (id: string, assertion: () => Promise<string | void>): Promise<void> => { if (seen.has(id)) throw new Error(`duplicate ${id}`); seen.add(id); try { const detail = await assertion(); checks.push({ id, status: "PASS", detail: detail ?? "passed" }); } catch (error: unknown) { checks.push({ id, status: "FAIL", detail: error instanceof Error ? error.message : String(error) }); } };
  const browser = await puppeteer.launch({ headless: true, executablePath: options.executablePath ?? nodeProcess.env.CHROME_PATH ?? "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", args: ["--no-sandbox", "--disable-dev-shm-usage"] });
  const page = await browser.newPage();
  // A blank page has no base URL, so a relative fetch cannot resolve.
  // Load the site first. This checks the server before the 80 assertions blame their own subject for a missing server.
  await go(page, options.url, "/");
  const mechanics = rec(await getJson(page, "/data/mechanics.json")); const runtime = rec(await getJson(page, "/data/runtime-evidence.json")); const external = rec(await getJson(page, "/data/external-leaf-evidence.json"));
  if (typeof mechanics.buildId !== "string" || typeof runtime.buildId !== "string" || !external) throw new Error("published evidence is malformed");
  for (const id of DOCS) {
    const document = docs(mechanics).find((value) => value.id === id); if (document === undefined) throw new Error(`missing document ${id}`); await go(page, options.url, GUIDE_ROUTES[id]!);
    const fields = textList(document);
    await emit(`guide-contract.${id}`, async () => { if (arr(document, "sourceTargets").length === 0) throw new Error("source target list is empty"); for (const item of fields) if (item.evidence.kind !== "editorial" && item.evidence.requiredProbes.some((entry) => entry.contractSha256.length !== 64)) throw new Error(`invalid probe contract ${item.id}`); });
    await emit(`guide-text.${id}`, async () => { const expected = fields.map((item) => ({ id: item.id, text: item.text })); await page.evaluate((values) => { const nodes = Array.from(document.querySelectorAll<HTMLElement>("[data-mechanic-text]")); if (nodes.length !== values.length) throw new Error("text count mismatch"); nodes.forEach((node, index) => { const value = values[index]!; if (node.dataset.mechanicText !== value.id) throw new Error(`text mismatch ${value.id}`); if (node.dataset.mechanicTable === undefined) { if (node.textContent?.trim() !== value.text) throw new Error(`text mismatch ${value.id}`); return; } let expectedRows: unknown; try { expectedRows = JSON.parse(value.text); } catch { throw new Error(`invalid table JSON ${value.id}`); } if (!Array.isArray(expectedRows)) throw new Error(`table rows missing ${value.id}`); const columns = Array.from(node.querySelectorAll<HTMLElement>("thead [data-fact-column]"), (cell) => cell.dataset.factColumn).filter((column): column is string => column !== undefined); const rows = Array.from(node.querySelectorAll<HTMLTableRowElement>("tbody tr")); if (rows.length !== expectedRows.length) throw new Error(`table row count mismatch ${value.id}`); rows.forEach((row, rowIndex) => { const expectedRow = expectedRows[rowIndex] as Record<string, unknown>; const expectedKeys = Object.keys(expectedRow).sort(); const actualCells = Array.from(row.querySelectorAll<HTMLElement>("[data-fact-cell]")); const actualKeys = actualCells.map((cell) => cell.dataset.factCell).filter((key): key is string => key !== undefined).sort(); if (JSON.stringify(actualKeys) !== JSON.stringify(expectedKeys) || JSON.stringify([...columns].sort()) !== JSON.stringify(expectedKeys)) throw new Error(`table columns mismatch ${value.id}`); for (const cell of actualCells) { const key = cell.dataset.factCell; if (key === undefined) throw new Error(`table cell key missing ${value.id}`); const expectedCell = expectedRow[key]; const rawValue = cell.dataset.factValue; if (rawValue === undefined || rawValue !== String(expectedCell)) throw new Error(`table cell mismatch ${value.id}.${key}`); } }); }); }, expected); });
    await emit(`guide-hrefs.${id}`, async () => { const expected = arr(document, "related").map((value) => { const link = rec(value); const href = text(link.href); return { id: href.id, text: href.text }; }); await page.evaluate((values) => { const nodes = Array.from(document.querySelectorAll<HTMLAnchorElement>("[data-mechanic-href]")); if (nodes.length !== values.length) throw new Error("href count mismatch"); nodes.forEach((node, index) => { if (node.dataset.mechanicHref !== values[index]!.id || node.getAttribute("href") !== values[index]!.text || node.dataset.hrefVerification !== "editorial") throw new Error(`href mismatch ${values[index]!.id}`); }); }, expected); });
    await emit(`guide-provenance.${id}`, async () => { const expected = fields.map((item) => ({ id: item.id, status: expectedStatus(item, mechanics, runtime) })); await page.evaluate((values) => { for (const value of values) { const node = document.querySelector<HTMLElement>(`[data-mechanic-text="${CSS.escape(value.id)}"]`); if (!node || node.dataset.verification !== value.status) throw new Error(`status mismatch ${value.id}`); const label = node.parentElement?.querySelector("[data-verification-label]")?.textContent?.trim(); const expected = value.status === "editorial" ? "Compendium wording" : value.status === "source-verified" ? "Source checked" : "Live checked"; if (label !== expected) throw new Error(`label mismatch ${value.id}`); } }, expected); });
    await emit(`index-card.${id}`, async () => { await go(page, options.url, "/mechanics/"); const live = formulaAndFactTexts(document).some((item) => expectedStatus(item, mechanics, runtime) === "live-verified"); await page.evaluate((idValue, liveValue) => { const card = document.querySelector<HTMLElement>(`[data-mechanic-card="${CSS.escape(idValue)}"]`); if (!card) throw new Error(`missing guide card ${idValue}`); const label = liveValue ? "Game claims: Source checked · selected content live checked" : "Game claims: Source checked"; if (!(card.textContent ?? "").includes(label)) throw new Error(`card label mismatch ${idValue}`); }, id, live); });
  }
  await emit("endgame-copy", async () => { const document = docs(mechanics).find((value) => value.id === "endgame-systems"); if (!document) throw new Error("missing endgame"); await go(page, options.url, GUIDE_ROUTES["endgame-systems"]!); const sections = arr(document, "sections"); const titles = sections.map((value) => text(rec(value).title).text); const bullets = sections.flatMap((value) => arr(rec(value), "bullets").map((bullet) => text(bullet).text)); await page.evaluate((expected) => { const actual = Array.from(document.querySelectorAll<HTMLElement>("[data-mechanic-section-title]"), (node) => node.textContent?.trim() ?? ""); if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error("endgame title order mismatch"); }, titles); await page.evaluate((expected) => { const actual = Array.from(document.querySelectorAll<HTMLElement>("[data-game-bullet]"), (node) => node.textContent?.trim() ?? ""); if (JSON.stringify(actual) !== JSON.stringify(expected)) throw new Error("endgame bullet order mismatch"); }, bullets); });
  await emit("endgame-counts", async () => { const document = docs(mechanics).find((value) => value.id === "endgame-systems"); if (!document || arr(document, "sections").length !== 11 || arr(document, "sections").reduce((sum, value) => sum + arr(rec(value), "bullets").length, 0) !== 63) throw new Error("endgame count mismatch"); });
  for (const route of ROUTES) { await emit(`no-internals.${route}`, async () => { await go(page, options.url, route); const body = await visibleText(page); if (FORBIDDEN.some((pattern) => pattern.test(body))) throw new Error(`internal vocabulary in ${route}`); }); await emit(`smoke.${route}`, async () => { const consoleErrors: string[] = []; const failedImageResponses: string[] = []; const listener = (message: { type(): string; text(): string }) => { if (message.type() === "error") consoleErrors.push(message.text()); }; const responseListener = (response: { request(): { resourceType(): string }; ok(): boolean; url(): string; status(): number }) => { if (response.request().resourceType() === "image" && !response.ok()) failedImageResponses.push(`${response.url()} (${response.status()})`); }; page.on("console", listener); page.on("response", responseListener); try { await go(page, options.url, route); const imageState = await page.evaluate(() => ({ zeroWidth: Array.from(document.images).filter((image) => image.complete && image.naturalWidth === 0).map((image) => image.currentSrc || image.src) })); const broken = [...failedImageResponses, ...imageState.zeroWidth]; if (broken.length > 0) throw new Error(`broken images ${[...new Set([...failedImageResponses, ...broken])].join(", ")}`); } finally { page.off("console", listener); page.off("response", responseListener); } if (consoleErrors.length > 0) throw new Error(`console errors: ${consoleErrors.join(" | ")}`); }); }
  for (const table of TABLES) await emit(`mapped-link.${table}`, async () => { const slug = DATA_SLUG_FOR_CHECK[table] ?? table; await go(page, options.url, `/${slug}/`); const dataTable = DATA_TABLE_FOR_CHECK[table] ?? table; const values = await getJson(page, `/data/${dataTable}.json`); if (!Array.isArray(values) || values.length === 0) throw new Error(`empty ${dataTable}`); let selected: { id: string; route: string } | null = null; for (const value of values) { const first = rec(value); const id = detailId(first); if (id === null) continue; const route = `/${slug}/${encodeURIComponent(id)}/`; const response = await page.goto(new URL(route, options.url).href, { waitUntil: "domcontentloaded" }); if (response !== null && response.ok()) { selected = { id, route }; break; } } if (selected === null) throw new Error(`no prerendered detail page for ${dataTable}`); const expected = `/mechanics/${GUIDE_FOR_TABLE[table]!}/`; await page.evaluate((href) => { const block = document.querySelector("[data-mechanic-links]"); const fields = document.querySelector("[data-detail-fields]"); if (!block || !fields || (block.compareDocumentPosition(fields) & Node.DOCUMENT_POSITION_FOLLOWING) === 0) throw new Error("mechanic link order missing"); if (!Array.from(block.querySelectorAll<HTMLAnchorElement>("a")).some((link) => new URL(link.href, location.href).pathname === href)) throw new Error(`missing ${href}`); }, expected); return `selected id=${selected.id} url=${selected.route}`; });
  await emit("progression-links", async () => { await go(page, options.url, "/progression/"); await page.evaluate(() => { if (!Array.from(document.links).some((link) => new URL(link.href, location.href).pathname === "/mechanics/endgame-systems/")) throw new Error("progression guide link missing"); }); await go(page, options.url, "/mechanics/endgame-systems/"); await page.evaluate(() => { if (!Array.from(document.links).some((link) => new URL(link.href, location.href).pathname === "/progression/")) throw new Error("endgame progression link missing"); }); });
  for (const query of SEARCHES) await emit(`search.${query}`, async () => { await go(page, options.url, "/"); const input = await page.$('input[role="combobox"]'); if (!input) throw new Error("search missing"); await input.focus(); await page.keyboard.type(query); await new Promise((resolve) => setTimeout(resolve, 150)); await page.keyboard.press("Enter"); await new Promise((resolve) => setTimeout(resolve, 150)); if (!page.url().includes("/mechanics/")) throw new Error(`search ${query} did not open guide`); });
  await emit("combobox-ids", async () => { await go(page, options.url, "/items/"); await page.evaluate(() => { const ids = Array.from(document.querySelectorAll("[id]"), (node) => node.id); if (new Set(ids).size !== ids.length) throw new Error("duplicate IDs"); for (const input of Array.from(document.querySelectorAll<HTMLInputElement>('[role="combobox"]'))) { const listbox = document.getElementById(input.getAttribute("aria-controls") ?? ""); if (!listbox || listbox.getAttribute("role") !== "listbox") throw new Error("combobox controls missing listbox"); const active = input.getAttribute("aria-activedescendant"); if (active && document.getElementById(active)?.getAttribute("role") !== "option") throw new Error("active descendant invalid"); } }); });
  await emit("lazy-search-transfer", async () => { await go(page, options.url, "/items/"); let count = 0; const listener = (request: { url(): string }) => { if (request.url().endsWith("/data/search_index.json")) count += 1; }; page.on("request", listener); await new Promise((resolve) => setTimeout(resolve, 50)); if (count !== 0) throw new Error("search transferred before focus"); const input = await page.$('input[role="combobox"]'); if (!input) throw new Error("search missing"); await input.focus(); await page.keyboard.type("defense"); await new Promise((resolve) => setTimeout(resolve, 300)); page.off("request", listener); if (count !== 1) throw new Error(`expected one search transfer, got ${count}`); });
  await emit("search-keyboard", async () => { await go(page, options.url, "/"); await page.evaluate(() => { const active = document.activeElement; if (active instanceof HTMLElement && active.matches('input[role="combobox"]')) throw new Error("search initially focused"); }); const input = await page.$('input[role="combobox"]'); if (!input) throw new Error("search missing"); let focused = false; for (let attempt = 0; attempt < 3 && !focused; attempt += 1) { await page.keyboard.press("/"); try { await page.waitForFunction(() => document.activeElement?.matches('input[role="combobox"]'), { timeout: 300 }); focused = true; } catch { await page.evaluate(() => new Promise<void>((resolve) => requestAnimationFrame(() => resolve()))); } } if (!focused) throw new Error("slash shortcut did not focus search"); await page.keyboard.press("Escape"); const state = await input.evaluate((node) => ({ value: node instanceof HTMLInputElement ? node.value : null, focused: document.activeElement === node })); if (state.value !== "" || !state.focused) throw new Error(`Escape focus behavior failed value=${state.value ?? "non-input"} focused=${state.focused}`); });
  await emit("desktop-fold", async () => { await page.setViewport({ width: 1440, height: 900 }); await go(page, options.url, "/"); await page.evaluate(() => { const landmarks = [document.querySelector("h1"), document.querySelector('input[role="combobox"]'), ...Array.from(document.querySelectorAll("h2,h3")).filter((node) => node.textContent?.includes("Understand the game"))]; if (landmarks.some((node) => !node)) throw new Error("home landmarks missing"); for (const node of landmarks) { const box = node!.getBoundingClientRect(); if (box.top >= innerHeight || box.bottom <= 0) throw new Error("landmark below fold"); } const index = document.querySelector("[data-compendium-index]"); if (index && index.getBoundingClientRect().top < innerHeight) throw new Error("index in first viewport"); }); });
  for (const viewport of VIEWPORTS) await emit(`responsive.${viewport.id}`, async () => { await page.setViewport({ width: viewport.width, height: viewport.height }); await go(page, options.url, "/"); const undersized = await page.evaluate(() => { const skip = document.querySelector<HTMLElement>("a.skip"); skip?.focus({ preventScroll: true }); const failures: string[] = []; const label = (node: HTMLElement): string => { const aria = node.getAttribute("aria-label"); if (aria) return aria; const text = node.textContent?.trim().replace(/\s+/g, " "); return text ? text.slice(0, 48) : node.tagName.toLowerCase(); }; for (const node of Array.from(document.querySelectorAll<HTMLElement>("a,button,input,[role=button],summary"))) { const box = node.getBoundingClientRect(); const style = getComputedStyle(node); const visuallyHidden = style.display === "none" || style.visibility === "hidden" || style.opacity === "0" || box.width === 0 || box.height === 0 || box.right < -1000 || box.left > innerWidth + 1000 || box.bottom < -1000 || box.top > innerHeight + 1000; if (visuallyHidden && node !== document.activeElement) continue; if (box.width < 44 || box.height < 44) failures.push(`${node.tagName.toLowerCase()}[${label(node)}] ${Math.round(box.width)}x${Math.round(box.height)}`); } return failures; }); if (undersized.length > 0) throw new Error(`target below 44px: ${undersized.join(" | ")}`); await page.evaluate(() => { if (document.documentElement.scrollWidth !== document.documentElement.clientWidth) throw new Error("horizontal overflow"); for (const node of Array.from(document.querySelectorAll<HTMLElement>("*"))) if (node.getBoundingClientRect().right > innerWidth + 1 && !node.closest("[data-formula],.formula,.formula-block")) throw new Error("overflow outside formula"); }); });
  await emit("eager-image", async () => { const html = htmlFiles(nodePath.join(nodePath.resolve(import.meta.dirname, ".."), "site/build")).map((file) => readFileSync(file, "utf8")).join("\n"); if ((html.match(/loading=["']eager["']/g) ?? []).length !== 1 || (html.match(/fetchpriority=["']high["']/g) ?? []).length !== 1) throw new Error("eager image count mismatch"); });
  await emit("art-variants", async () => { await page.setViewport({ width: 1440, height: 900 }); await go(page, options.url, "/"); await page.evaluate(() => { const hero = Array.from(document.images).find((image) => image.getBoundingClientRect().width > 500); if (hero && !hero.currentSrc.includes("/hero/")) throw new Error("hero variant missing"); }); await go(page, options.url, "/classes/"); await page.evaluate(() => { for (const image of Array.from(document.images)) if (image.getBoundingClientRect().width > 100 && !image.currentSrc.includes("/portrait/")) throw new Error("class portrait variant missing"); }); });
  await emit("transfer-budget", async () => { await page.setViewport({ width: 1440, height: 900 }); await go(page, options.url, "/"); const entries = await page.evaluate(() => performance.getEntriesByType("resource").map((entry) => ({ name: entry.name, size: (entry as PerformanceResourceTiming).transferSize }))); const images = entries.filter((entry) => /\.(?:webp|png|jpg|jpeg)(?:\?|$)/i.test(entry.name)).reduce((sum, entry) => sum + entry.size, 0); const total = entries.reduce((sum, entry) => sum + entry.size, 0); if (images > 900 * 1024 || total > 1.1 * 1024 * 1024) throw new Error("transfer budget exceeded"); });
  await emit("prerender-content", async () => { const html = htmlFiles(nodePath.join(nodePath.resolve(import.meta.dirname, ".."), "site/build")).map((file) => readFileSync(file, "utf8")).join("\n"); for (const title of ["Combat Mathematics", "Ability Calculations", "Skills and Crafting", "Equipment and Item Value", "Endgame Systems"]) if (!html.includes(title)) throw new Error(`missing ${title}`); const formula = gameFormulaText(mechanics); if (!html.includes(formula)) throw new Error(`missing game-authored formula ${formula}`); if (!html.includes("impeccable:direction vespera-expedition-ledger")) throw new Error("missing direction contract"); if (/MISSING ART/.test(html) && !html.includes("initials")) throw new Error("unexpected missing art"); });
  await browser.close(); if (options.resultPath) atomicWrite(options.resultPath, { version: 1, checks, generatedAt: new Date().toISOString() }); return checks;
}

export function runVerifySiteBrowserCli(argv: readonly string[] = nodeProcess.argv.slice(2)): void { const index = argv.indexOf("--url"); if (index < 0 || !argv[index + 1]) { console.log("usage: bun run tools/verify-site-browser.ts --url <baseUrl> [--chrome <executable>]"); return; } const chrome = argv.indexOf("--chrome"); let checks: Result[] | null = null; verifySiteBrowser({ url: argv[index + 1]!, executablePath: chrome >= 0 ? argv[chrome + 1] : undefined, resultPath: nodePath.resolve(nodeProcess.env.EVIDENCE_ROOT ?? "evidence", "site-browser-checks.json") }).then((result) => { checks = result; const expected = [...SITE_BROWSER_CHECK_IDS]; const actual = result.map((check) => check.id); const missing = expected.filter((id) => !actual.includes(id)); const extra = actual.filter((id) => !expected.includes(id)); const duplicates = actual.filter((id, index) => actual.indexOf(id) !== index); const failed = result.filter((check) => check.status !== "PASS"); if (missing.length || extra.length || duplicates.length || failed.length) throw new Error(`browser checks failed missing=${missing.join(",")} extra=${extra.join(",")} duplicate=${duplicates.join(",")} failed=${failed.map((check) => check.id).join(",")}`); }).catch((error: unknown) => { const detail = error instanceof Error ? error.message : String(error); console.error(detail); const failedChecks = checks ?? SITE_BROWSER_CHECK_IDS.map((id) => ({ id, status: "FAIL" as const, detail: `verification aborted: ${detail}` })); atomicWrite(nodePath.resolve(nodeProcess.env.EVIDENCE_ROOT ?? "evidence", "site-browser-checks.json"), { version: 1, checks: failedChecks, generatedAt: new Date().toISOString() }); nodeProcess.exitCode = 1; }); }
if (import.meta.main || nodeProcess.argv[1]?.endsWith("verify-site-browser.ts")) runVerifySiteBrowserCli();
